version: 2
formats: all

python:
      version: 3.7
      setup_py_install: true
      install:
            - requirements: doc/requirements.txt

sphinx:
      builder: html
      configuration: doc/sphinx/source/conf.py
