language: python
python:
      - "3.7"
before_install:
      - sudo apt-get install cmake libblas-dev liblapack-dev
install:
      - pip install -r requirements.txt
script:
      - nosetests
      - pylint srlife
