name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install cmake libblas-dev liblapack-dev python3-setuptools python3-pip python3-dev
        pip3 install --user setuptools wheel twine
        pip3 install --user -r requirements.txt
    - name: Test twine
      run: which twine3
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 setup.py sdist bdist_wheel
        twine3 upload dist/*
