name: tests
on: [push, pull_request]
jobs:
      test-linux:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install cmake libblas-dev liblapack-dev python3-setuptools python3-pip python3-dev python3-pip python3-nose python3-pylint
            - run: pip3 install --user wheel
            - run: pip3 install --user -r requirements.txt
            - run: nosetests3
            - run: pylint3 srlife

