name: tests
on: [push, pull_request]
jobs:
      test-linux:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install cmake libblas-dev liblapack-dev
            - run: python3 --version
            - run: sudo pip3 install -r requirements.txt
            - run: nosetests3
            - run: pylint3 srlife

