name: tests
on: [push, pull_request]
jobs:
      test-linux:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install cmake libblas-dev liblapack-dev
            - run: pip install -r requirements.txt
            - run: nosetests
            - run: pylint srlife

